In [1]:
import numpy as np
import pandas as pd

In [2]:
import os
os.chdir("../")

In [3]:
data = pd.read_csv("./datasets/CAR DETAILS FROM CAR DEKHO.xls")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [4]:
from utils.LabelEncoder import LabelEncoder
le = LabelEncoder()
data["label_encoded_transmission"] = le.fit_transform(data["transmission"]).astype(np.int32)
data["label_encoded_fuel"] = le.fit_transform(data["fuel"]).astype(np.int32)
data["label_encoded_seller_type"] = le.fit_transform(data["seller_type"]).astype(np.int32)
data["label_encoded_owner"] = le.fit_transform(data["owner"]).astype(np.int32)
from utils.StandardScaler import StandardScaler
data = data.drop(["fuel","seller_type","owner","transmission","name"],axis=1)
sc = StandardScaler()
data = sc.transform(data)

x = data.drop(["selling_price"],axis=1)
y = data["selling_price"]
X = x.to_numpy()
Y = y.to_numpy()

In [5]:
x_train,x_test = X[:3000],X[3000:]
y_train,y_test = Y[:3000],Y[3000:]

Mean Squared Error
$$
\text{MSE} = \frac{1}{n} \sum_{i=1}^{n} (y_i - (mx_i + b))^2
$$
Partial derivative of MSE with respect to b :
$$
\frac{\partial}{\partial b} \text{MSE} = \frac{2}{n} \sum_{i=1}^{n} x_i \left( y_i - (m x_i + b)\right)
$$
Partial derivative of MSE with respect to  m :
$$
\frac{\partial}{\partial m} \text{MSE} = \frac{-2}{n} \sum_{i=1}^{n} \left( y_i - (mx_i + b)\right)
$$

In [15]:
def fit(x,y,lr):
    w = np.zeros(x.shape[1])
    b = 0
    for i in range(20):
        # print(w)
        y_pred = np.dot(x,w) + b
        db = 2/x.shape[0] * np.sum(y_pred-y)
        dw = 2/x.shape[0] * np.dot((y_pred-y),x)
        print(dw,db)
        b = b - lr * db
        w = w - lr * dw
    return w,b
w,b = fit(x_train,y_train,0.0001)
# w,b = fit(X,Y,0.001)

[-0.86948592  0.42244089 -1.1809813  -0.49026128 -0.55186548  0.38671804] -0.03910975932993365
[-0.86917955  0.42223391 -1.18065661 -0.49016791 -0.55162098  0.38650954] -0.039090342404404455
[-0.8688733   0.42202702 -1.18033201 -0.49007455 -0.55137657  0.38630113] -0.039070934001113236
[-0.86856716  0.42182022 -1.18000751 -0.4899812  -0.55113227  0.38609281] -0.0390515341165098
[-0.86826114  0.42161352 -1.17968311 -0.48988786 -0.55088806  0.38588458] -0.03903214274704552
[-0.86795524  0.42140691 -1.17935881 -0.48979454 -0.55064395  0.38567645] -0.03901275988917325
[-0.86764945  0.42120039 -1.17903461 -0.48970123 -0.55039995  0.38546841] -0.03899338553934712
[-0.86734378  0.42099397 -1.17871051 -0.48960794 -0.55015604  0.38526045] -0.03897401969402286
[-0.86703822  0.42078764 -1.17838651 -0.48951465 -0.54991223  0.3850526 ] -0.038954662349657554
[-0.86673278  0.42058139 -1.17806261 -0.48942138 -0.54966851  0.38484483] -0.03893531350270978
[-0.86642746  0.42037525 -1.17773881 -0.48932813

In [18]:
def predict(x):
    return np.dot(x,w) + b
pred = predict(x_test)

In [19]:
def mse(y,pred):
    print(y)
    print(pred)
    return np.mean((pred - y)**2)
print(mse(y_test,pred))

[-0.43924962 -0.7330883   0.64103967 ... -0.68123442  0.62375504
 -0.48246119]
[-0.00261736 -0.00480287  0.00136709 ... -0.00468967  0.00072888
 -0.00015043]
0.8205990784821707
